FileVersion = 1
Projects = {OpenGL = {Path = "OpenGL"}, OpenGLTest = {Path = "OpenGLTest"}}

[Workspace]
StartupProject = "OpenGLTest"

[Configs.Test.Win32]
ConfigSelections = {corlib = {Config = "Debug"}}

[Configs.Test.Win64]
ConfigSelections = {corlib = {Config = "Debug"}}
